# Generated by Django 3.1.1 on 2020-12-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('pin_code', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
