# Generated by Django 3.1.1 on 2020-10-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20201005_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_list',
            old_name='user',
            new_name='author',
        ),
    ]
